/*global systemDictionary:true */
"use strict";

systemDictionary = {
  "Main settings":        { "en": "Main settings", "de": "Haupteinstellungen", "ru": "Основные параметры", "pt": "Configurações principais", "nl": "Belangrijkste instellingen", "fr": "Réglages principaux", "it": "Impostazioni principali", "es": "Ajustes principales", "pl": "Ustawienia główne", "zh-cn": "主要设定" },
  "Select the medium":    { "en": "Select the medium", "de": "Wähle das Medium aus", "ru": "Wähle das Medium aus", "pt": "Wähle das Medium aus", "nl": "Wähle das Medium aus", "fr": "Wähle das Medium aus", "it": "Wähle das Medium aus", "es": "Wähle das Medium aus", "pl": "Wähle das Medium aus", "zh-cn": "Wähle das Medium aus" },
  "Oil":                  { "en": "Oil", "de": "Öl", "ru": "Öl", "pt": "Öl", "nl": "Öl", "fr": "Öl", "it": "Öl", "es": "Öl", "pl": "Öl", "zh-cn": "Öl" },
  "Water":                { "en": "Water", "de": "Wasser", "ru": "Wasser", "pt": "Wasser", "nl": "Wasser", "fr": "Wasser", "it": "Wasser", "es": "Wasser", "pl": "Wasser", "zh-cn": "Wasser" },
  "Medium":               { "en": "Medium", "de": "Medium", "ru": "Medium", "pt": "Medium", "nl": "Medium", "fr": "Medium", "it": "Medium", "es": "Medium", "pl": "Medium", "zh-cn": "Medium" },
  "Day":                  { "en": "Day", "de": "Tag", "ru": "День", "pt": "Dia", "nl": "Dag", "fr": "Jour", "it": "Giorno", "es": "Día", "pl": "Dzień", "zh-cn": "日" },
  "Week":                 { "en": "Week", "de": "Woche", "ru": "Woche", "pt": "Woche", "nl": "Woche", "fr": "Woche", "it": "Woche", "es": "Woche", "pl": "Woche", "zh-cn": "Woche" },
  "Month":                { "en": "Month", "de": "Monat", "ru": "Monat", "pt": "Monat", "nl": "Monat", "fr": "Monat", "it": "Monat", "es": "Monat", "pl": "Monat", "zh-cn": "Monat" },
  "Year":                 { "en": "Year", "de": "Jahr", "ru": "Jahr", "pt": "Jahr", "nl": "Jahr", "fr": "Jahr", "it": "Jahr", "es": "Jahr", "pl": "Jahr", "zh-cn": "Jahr" },
  "Select":               { "en": "Select", "de": "Auswählen", "ru": "Select", "pt": "Select", "nl": "Select", "fr": "Select", "it": "Select", "es": "Select", "pl": "Select", "zh-cn": "Select" },
  "Cancel":               { "en": "Cancel", "de": "Abbruch", "ru": "Cancel", "pt": "Cancel", "nl": "Cancel", "fr": "Cancel", "it": "Cancel", "es": "Cancel", "pl": "Cancel", "zh-cn": "Cancel" },
  "on save adapter restarts with new config immediately": { "en": "when saving, adapter restarts with new config immediately",  "de": "Beim Speichern von Einstellungen der Adapter wird sofort neu gestartet.",  "ru": "При сохранении настроек адаптера он сразу же перезапускается",  "pt": "no adaptador de salvar reinicia com nova configuração imediatamente",  "nl": "Naar het opslaan wordt de adapter onmiddellijk opnieuw gestart met de nieuwe configuratie",  "fr": "sur l'adaptateur de sauvegarde redémarre avec la nouvelle config immédiatement",  "it": "Con il salvataggio delle impostazioni dell'adattatore, si riavvia immediatamente con la configurazione nuova",  "es": "en el adaptador de guardar se reinicia con nueva configuración de inmediato",  "pl": "na karcie save natychmiast uruchamia się z nową konfiguracją",  "zh-cn": "保存适配器立即重新启动新配置" }
};