/*global systemDictionary:true */
"use strict";

systemDictionary = {
  "Main settings":                          { "en": "Main settings",                          "de": "Haupteinstellungen",                     "ru": "Основные параметры",                           "uk":"Основні налаштування",                                    "pt": "Configurações principais",                           "nl": "Belangrijkste instellingen",             "fr": "Réglages principaux",                                  "it": "Impostazioni principali",                        "es": "Ajustes principales",                                  "pl": "Ustawienia główne",                                            "zh-cn": "主要设定" },
  "Object ID: (oil tank level in liters)":  { "en": "Object ID: (oil tank level in liters)",  "de": "Objekt-ID: (Öltank Füllstand in Liter)", "ru": "ID объекта: (уровень масла в баке в литрах)",  "uk": "Ідентифікатор об'єкта: (рівень масла в баку в літрах)",  "pt": "ID do objeto: (nível do tanque de óleo em litros)",  "nl": "Object-ID: (olietankniveau in liters)",  "fr": "ID d'objet : (niveau du réservoir d'huile en litres)", "it": "ID oggetto: (livello serbatoio olio in litri)",  "es": "ID de objeto: (nivel del tanque de aceite en litros)", "pl": "Identyfikator obiektu: (poziom oleju w zbiorniku w litrach)",  "zh-cn": "對象 ID：（以升為單位的油箱液位）"},
  "Select the medium":                      { "en": "Select the medium",                      "de": "Wähle das Medium aus",                   "ru": "Выберите среду",                               "uk":"Виберіть засіб",                                          "pt": "Selecione o meio",                                   "nl": "Selecteer het medium",                   "fr": "Sélectionnez le support",                              "it": "Seleziona il mezzo",                             "es": "Seleccione el medio",                                  "pl": "Wybierz nośnik",                                               "zh-cn": "選擇介質" },
  "Oil":                                    { "en": "Oil",                                    "de": "Öl",                                     "ru": "Масло",                                        "uk":"олія",                                                    "pt": "Óleo",                                               "nl": "Olie",                                   "fr": "Pétrole",                                              "it": "Il petrolio",                                    "es": "Petróleo",                                             "pl": "Olej",                                                         "zh-cn": "油" },
  "Water":                                  { "en": "Water",                                  "de": "Wasser",                                 "ru": "Вода",                                         "uk":"вода",                                                    "pt": "Água",                                               "nl": "Water",                                  "fr": "Eau",                                                  "it": "Acqua",                                          "es": "Agua",                                                 "pl": "Woda",                                                         "zh-cn": "水" },
  "Medium":                                 { "en": "Medium",                                 "de": "Medium",                                 "ru": "Середина",                                     "uk":"Середній",                                                "pt": "Média",                                              "nl": "Medium",                                 "fr": "Moyen",                                                "it": "medio",                                          "es": "Medio",                                                "pl": "Średni",                                                       "zh-cn": "中等的" },
  "Day":                                    { "en": "Day",                                    "de": "Tag",                                    "ru": "День",                                         "uk":"День",                                                    "pt": "Dia",                                                "nl": "Dag",                                    "fr": "Jour",                                                 "it": "Giorno",                                         "es": "Día",                                                  "pl": "Dzień",                                                        "zh-cn": "日" },
  "Week":                                   { "en": "Week",                                   "de": "Woche",                                  "ru": "Неделю",                                       "uk":"тиждень",                                                 "pt": "Semana",                                             "nl": "Week",                                   "fr": "Semaine",                                              "it": "Settimana",                                      "es": "Semana",                                               "pl": "Tydzień",                                                      "zh-cn": "星期" },
  "Month":                                  { "en": "Month",                                  "de": "Monat",                                  "ru": "Месяц",                                        "uk":"місяць",                                                  "pt": "Mês",                                                "nl": "Maand",                                  "fr": "Mois",                                                 "it": "Mese",                                           "es": "Mes",                                                  "pl": "Miesiąc",                                                      "zh-cn": "月" },
  "Year":                                   { "en": "Year",                                   "de": "Jahr",                                   "ru": "Год",                                          "uk":"рік",                                                     "pt": "Ano",                                                "nl": "Jaar",                                   "fr": "An",                                                   "it": "Anno",                                           "es": "Año",                                                  "pl": "Rok",                                                          "zh-cn": "年" },
  "Select":                                 { "en": "Select",                                 "de": "Auswählen",                              "ru": "Выбирать",                                     "uk":"Виберіть",                                                "pt": "Selecione",                                          "nl": "Selecteer",                              "fr": "Sélectionner",                                         "it": "Selezionare",                                    "es": "Seleccione",                                           "pl": "Wybierać",                                                     "zh-cn": "選擇" },
  "Cancel":                                 { "en": "Cancel",                                 "de": "Abbruch",                                "ru": "Отмена",                                       "uk":"Скасувати",                                               "pt": "Cancelar",                                           "nl": "Annuleren",                              "fr": "Annuler",                                              "it": "Annulla",                                        "es": "Cancelar",                                             "pl": "anulować",                                                     "zh-cn": "取消" },
  "on save adapter restarts with new config immediately": { "en": "When saving, adapter restarts with new config immediately",  "de": "Beim Speichern von Einstellungen der Adapter wird sofort neu gestartet.",  "ru": "При сохранении настроек адаптера он сразу же перезапускается",  "uk": "Під час збереження адаптер негайно перезавантажується з новою конфігурацією",  "pt": "no adaptador de salvar reinicia com nova configuração imediatamente",  "nl": "Naar het opslaan wordt de adapter onmiddellijk opnieuw gestart met de nieuwe configuratie",  "fr": "sur l'adaptateur de sauvegarde redémarre avec la nouvelle config immédiatement",  "it": "Con il salvataggio delle impostazioni dell'adattatore, si riavvia immediatamente con la configurazione nuova",  "es": "en el adaptador de guardar se reinicia con nueva configuración de inmediato",  "pl": "na karcie save natychmiast uruchamia się z nową konfiguracją",  "zh-cn": "保存适配器立即重新启动新配置" }
};